import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/components/AuthNavbar/Navbar';
import localFont from 'next/font/local';

const roboto = localFont({ src: '../../fonts/Roboto.woff2' });

export const metadata: Metadata = {
  title: 'Register For NetFlex Clone',
  description: 'Generated by create next app',
  authors: [{ name: 'Mina Mamdouh Helmy' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} auth-bg flex flex-col`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
