import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/components/Navbar/Navbar';
import localFont from 'next/font/local';

const roboto = localFont({ src: '../../fonts/Roboto.woff2' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className}`}>
        <Navbar />
        {/* <Navbar2 /> */}
        {children}
      </body>
    </html>
  );
}
