import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Register For NetFlex Clone',
  description: 'Generated by create next app',
  authors: [{ name: 'Mina Mamdouh Helmy' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className='overflow-hidden'>
          {children}
        </div>
  );
}
